### ISSUE TITLE
Launch Home Assistant on Boot

### ISSUE THREAD

**Issue by byte-bender** [balloob/home-assistant.io#103]
This comment refers to the systemd subpage of https://home-assistant.io/getting-started/autostart.html

There is one dash missing in the Reload system-d, it should be:

    sudo systemctl –-system daemon-reload

Further, did the ExecStart command "hass" lead to the follwing error on my raspberry pi 2 with raspbian jessie:

Oct 25 07:41:47 raspberrypi systemd[1]: [/lib/systemd/system/home-assistant.service:7] Executable path is not absolute...: hass
Oct 25 07:41:47 raspberrypi systemd[1]: home-assistant.service lacks ExecStart setting. Refusing.

It worked after changing it to the absolute path:

    /usr/local/bin/hass

To use the configuration of the user pi (and not root), I had to add the following line in the service section of the home-assistant.service file:

    User=pi

**Comment by balloob** [comment]
Oh that's nasty, the double dash was there but it looks like our syntax formatter or markdowm formatter replaces it with a hyphen.

Thanks for your report, I've updated the autostart page in 7a9fd7b622c30964978165b704d9fe245c3274a7
