### ISSUE TITLE
LOGBOOK_ENTRY seems to must be in uppercase

### ISSUE THREAD

**Issue by maximkrusina** [balloob/home-assistant.io#133]
Trying to use custom event loggin.

This exaple doesn't work for me:
https://home-assistant.io/components/script/
lowercase:       - event: logbook_entry

This works:
https://home-assistant.io/components/logbook/
uppercase:       - event: LOGBOOK_ENTRY

Tried several times, using 0.10.1

**Comment by balloob** [comment]
Ah yes, you are correct. It should have been lowercase all along.

I fixed this in balloob/home-assistant@987282da78381180973675ac77407c06f08b35d6 - it will now allow both but prefer the lowercase one.
