### ISSUE TITLE
Update Arduino Sensor Component to show Digital In Option

### ISSUE THREAD

**Issue by ryanturner** [balloob/home-assistant.io#144]
Right now it states:
type: The type of the pin. At the moment only ‘analog’ is supported.

However source shows that digital is supported as well.

**Comment by balloob** [comment]
Please next time can you open a PR with the change applied? The source code for this component can for example be found [here](https://github.com/balloob/home-assistant.io/blob/master/source/_components/sensor.arduino.markdown).
