### ISSUE TITLE
Add a "cookbook"

### ISSUE THREAD

**Issue by SamMousa** [balloob/home-assistant.io#149]
It would be great if there was an automation cookbook on the website where users can show their automations.
I feel a lot of stuff is not so much about the technical stuff as it is about the creativity.
Looking at other peoples' automations can inspire others!

-- I have a simple automation that i really like:
1. I listen to music on my PC using VLC.
2. I watch shows / movies on my TV using Kodi.
3. When Kodi changes to the playing state, vlc is muted via a commandline switch that uses curl to set the volume to 0.

**Comment by fabaff** [comment]
The [Configuration Cookbook](https://home-assistant.io/cookbook/) was created for sharing details. 

If your want to share something please create a PR against the `next` branch in this repo. Source for "recipes" is located [here](hhttps://github.com/balloob/home-assistant.io/tree/master/source/_cookbook).

**Comment by SamMousa** [comment]
Sorry I'm blind.. This can be closed!
