### ISSUE TITLE
Netatmo Feature Request

### ISSUE THREAD

**Issue by MrBenjaminHDM** [balloob/home-assistant.io#27]
Hello, I think that Netatmo would make a great addition to this controller. Netatmo have an API and I've seen it implemented quite well in things like ImperiHome for android.

**Comment by fabaff** [comment]
This is the repository for the documentation of Home Assistant. Can you please open a feature request in the [Home Assistant issue tracker](https://github.com/balloob/home-assistant)? Thanks.
