### ISSUE TITLE
Re-organisation of the installation section

### ISSUE THREAD

**Issue by fabaff** [balloob/home-assistant.io#28]
It seems that sooner or later we need additional guides about the installation. I think that at least a Windows section is needed. I started to write installation guides for Fedora, CentOS (because there is Firewalld and Systemd which needs special attention) and using a Cubieboard. Ok, right now it's more a transformation of my notes.

Do you guys think it worth to expand the installation section from the current state to cover more ground? Or should those guides be posted on the blog to keep the installation section clean?

**Comment by balloob** [comment]
It would be great if we could keep them all in 1 place. Maybe we should adopt the UI from [the BabelJS setup page](http://babeljs.io/docs/setup/)

Downside is of course maintenance but there shouldn't be many radical changes to our setup process.

**Comment by fabaff** [comment]
Sorry, I was not talking about splitting up things. I was thinking about to add more operating system-specific details like install needed packages, open firewall port, blablabla...

At least on Fedora, there is more needed than py3, git, and the 4 lines of setup in the quick start guide.

**Comment by fabaff** [comment]
So fare, just on page but more details -> https://home-assistant.io/getting-started/
