### ISSUE TITLE
WIKI page update/annotation fire-tv -- how to do? or by admin?

### ISSUE THREAD

**Issue by ozett** [balloob/home-assistant.io#286]
i was directed to github from wiki-page. 
really cool. (bytheway: how does this works?)

i found, that on the fire-tv wikipage a prerequisit is missing.
on my debian jessie i had to install 

apt-get install libssl-dev

to make the pip install for fire-tv sever.
https://github.com/balloob/home-assistant.io/blob/master/source/_components/media_player.firetv.markdown

maybe you want to mention this?

**Comment by fabaff** [comment]
Docs will be updated soon.
