### ISSUE TITLE
fire-tv module: ImportError: No module named 'cStringIO'

### ISSUE THREAD

**Issue by ozett** [balloob/home-assistant.io#287]
```bash
root@homeassistant:~# firetv-server 192.168.14.43:5555
Traceback (most recent call last):
  File "/usr/local/bin/firetv-server", line 7, in <module>
    from firetv.__main__ import main
  File "/usr/local/lib/python3.4/dist-packages/firetv/__init__.py", line 11, in <module>
    from adb import adb_commands
  File "/usr/local/lib/python3.4/dist-packages/adb/adb_commands.py", line 25, in <module>
    import cStringIO
ImportError: No module named 'cStringIO'
```
i did it like the wiki said.
have a debian jessie running.

root@homeassistant:~# python -V
Python 2.7.9

how to solve this python3/2 issue?
thanks for help!

edit: i looked here:
https://github.com/happyleavesaoc/python-firetv

but there is no hint for a noob like me how to pinn it to python 2...

**Comment by ozett** [comment]
one lead to another....

i had to remove firetv, because it was installed to my version 3 in my dual python environment.

than i had to install pip2 on my debian jessie

apt-get install python-pip

than i wanted firetv only for python2, i googled and found this:

python2.7 -m pip install firetv[firetv-server]

than flask was missing for python 2:

python2.7 -m pip install flask

than fire-tv run.

woooooohhhh

**Comment by Landrash** [comment]
I'm fairly certain this should be in the home-assistant repository. This repository is for the documentation.

**Comment by ozett** [comment]
the documentation here:
https://home-assistant.io/components/media_player.firetv/

states someway by-the-way that this is only for python2.

but the actual linux-systems already come mostly with python3. you can have dual install with python2, but i had to search a little bit in the web to see how this is made.

so it it would maybe of some help to be more expressed how to to the install to python2 (see my post before).

at the end it doesnt worked. i guess because i have auto-updated my fire-tv (v1, with optical out) to the least firmware (based on android5, i think). maybe something changed or it is blocked. 
dont know. the hassle was too much. i gave up on this...

**Comment by balloob** [comment]
FireTV needs Python 2 which is stated in the documentation.

It is out of scope for Home Assistant to provide support for every platform how to get different Python versions running.
