### ISSUE TITLE
Scene links don't work anymore

### ISSUE THREAD

**Issue by sander76** [balloob/home-assistant.io#301]
Just found out the links in the docs to the scene component don't work anymore.
This is obvious as the old scene has moved to scene.home-assistant.
What should we do ? Revert to the old scene or update the links ?

**Comment by fabaff** [comment]
Let's rename the file as the PowerView is part of the Roller shutter category.

**Comment by fabaff** [comment]
Fixed in https://github.com/balloob/home-assistant.io/commit/23f07633a882579c9303f1f3945bf9a35e45164e
