### ISSUE TITLE
Location of hass script

### ISSUE THREAD

**Issue by borpin** [balloob/home-assistant.io#368]
My install put the hass script into /usr/local/bin/ rather than /usr/bin/.

Suggest add an instruction to check location of hass with;

`whereis hass`

**Comment by fabaff** [comment]
Where do you think should we add this? In most use case (beside autostarting) this shouldn't matter because both are in PATH.

**Comment by borpin** [comment]
Sorry, I thought I'd linked it to the right page.  I'd suggest the autostart page.  In the sample systemd script is has a full path for the exec.  This failed when I tried it (as the script was not there).  I am aware that sometimes these instructions assume a lveel of knowledge that is not there.  These instructions are actually really, really good :)

Only other thing I found was installing pip3.  Simplest way on Debian based (such as raspbian) is 'sudo ap-get install python-pip3'.

Looks great so far. Good job.
