### ISSUE TITLE
Refactor component page

### ISSUE THREAD

**Issue by balloob** [balloob/home-assistant.io#43]
The new layout for the component page has helped a lot in making it more clear how the components work. I am however afraid that in the long run even this will turn into chaos. I think we should consider:
 - Splitting component page into three pages:
    - Devices (ie. Hue, MQTT, PushBullet)
    - Automation & Organization (ie. Automation, Scheduler, Group)
    - Functionality (ie. Logbook, Discovery)
 - Allow search/filter for device page ([example we can use](http://vestride.github.io/Shuffle/#demo), [example how it should look](http://www.google.com/cast/apps/#/gallery))

**Comment by fabaff** [comment]
To be honest, at the end I was disappointed with the new column-based layout because it didn't turn out to make the page shorter or more appealing. With new stuff coming on a daily base we are on the same track as before only with column, unfortunately.

**Comment by CCOSTAN** [comment]
That google cast example is really nice!

**Comment by balloob** [comment]
Closing issue as this is now fixed in master.
