### ISSUE TITLE
Wrong upgrade command

### ISSUE THREAD

**Issue by renekliment** [balloob/home-assistant.io#47]
There is an extra dash in the name of the HA at https://home-assistant.io/getting-started/ 
( `pip3 install --upgrade home-assistant` ). 

I'm sorry I'm too lazy to make a pull request.

**Comment by balloob** [comment]
If you click edit on the site it will allow you to make a pr when you click
save

**Comment by fabaff** [comment]
This was fixed with #38 but the page wasn't deploy.
