### ISSUE TITLE
(docs) MQTT QoS

### ISSUE THREAD

**Issue by renekliment** [balloob/home-assistant.io#48]
There is no QoS setting of the mqtt component - it should be removed at https://home-assistant.io/components/mqtt.html

However there are optional qos settings that should be mentioned here: https://home-assistant.io/components/switch.mqtt.html and here: https://home-assistant.io/components/sensor.mqtt.html

**Comment by fabaff** [comment]
Thanks for your report.

> There is no QoS setting of the mqtt component - it should be removed at https://home-assistant.io/components/mqtt.html

Yes, the information were outdated. Should be fixed now.

> However there are optional qos settings that should be mentioned here: https://home-assistant.io/components/switch.mqtt.html and here: https://home-assistant.io/components/sensor.mqtt.html

Those pages are already up-to-date but not deployed. I guess that the deployment will happen soon.
